# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e08e45527bd3a75b9d7ec7c7c62266a6d9c28c6d8a4db6c08cb2b20f34b2728cfc5eec693573633b12ce031d0633cf0699c3cb3dd9f2506abea880d48c185d

test:
  secret_key_base: 97d018b25a96c6a17a8ded2f02a0f07a9e69b35140ac55f554a91543ed9d727bb7908adb15aaced9a2798bf92a38e8f7e250c04b8dabbbbbb8d1c6c1e57a4531

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
